apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-coordinator
  labels:
    app: worldcompute
    component: coordinator
spec:
  serviceName: {{ .Release.Name }}-coordinator
  replicas: {{ .Values.coordinator.replicas }}
  selector:
    matchLabels:
      app: worldcompute
      component: coordinator
  template:
    metadata:
      labels:
        app: worldcompute
        component: coordinator
    spec:
      containers:
        - name: coordinator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["--role", "coordinator"]
          ports:
            - containerPort: 50051
              name: grpc
            - containerPort: 9090
              name: metrics
          resources:
            {{- toYaml .Values.coordinator.resources | nindent 12 }}
